apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  # echo -n 'djangopassword' | base64 -> ZGphbmdvcGFzc3dvcmQ=
  # echo -n 'rootpassword' | base64 -> cm9vdHBhc3N3b3Jk
  MYSQL_PASSWORD: ZGphbmdvcGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: default
type: Opaque
data:
  # echo -n 'a-very-strong-production-secret-key' | base64 -> YS12ZXJ5LXN0cm9uZy1wcm9kdWN0aW9uLXNlY3JldC1rZXk=
  SECRET_KEY: YS12ZXJ5LXN0cm9uZy1wcm9kdWN0aW9uLXNlY3JldC1rZXk=